# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-25 04:14
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Create_Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('Education', 'Education'), ('Fashion', 'Fashion'), ('Food', 'Food'), ('Other', 'Other')], default='Category', max_length=5)),
                ('type', models.CharField(choices=[('Fair', 'Fair'), ('Conference', 'Conference'), ('Party', 'Party'), ('Other', 'Other')], default='Types', max_length=5)),
                ('organizer', models.CharField(max_length=150)),
                ('Location', models.CharField(max_length=150)),
                ('start_date', models.DateField(default=datetime.datetime(2019, 1, 25, 4, 14, 8, 522040, tzinfo=utc))),
                ('end_date', models.DateField(default=datetime.datetime(2019, 1, 25, 4, 14, 8, 522040, tzinfo=utc))),
                ('start_time', models.TimeField(default='12:00')),
                ('end_time', models.TimeField(default='12:00')),
                ('image', models.ImageField(upload_to='events/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
