# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-25 04:30
from __future__ import unicode_literals

import ckeditor.fields
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('create_event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_event',
            name='description',
            field=ckeditor.fields.RichTextField(default=0),
        ),
        migrations.AlterField(
            model_name='create_event',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2019, 1, 25, 4, 30, 45, 825138, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='create_event',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2019, 1, 25, 4, 30, 45, 825138, tzinfo=utc)),
        ),
    ]
