# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-27 08:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('create_event', '0004_auto_20190125_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_event',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2019, 1, 27, 8, 3, 47, 405984, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='create_event',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2019, 1, 27, 8, 3, 47, 405984, tzinfo=utc)),
        ),
    ]
