# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-27 12:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('create_event', '0006_auto_20190127_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_event',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2019, 1, 27, 12, 50, 29, 642160, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='create_event',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2019, 1, 27, 12, 50, 29, 642160, tzinfo=utc)),
        ),
    ]
