# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-27 13:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('create_event', '0007_auto_20190127_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_event',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2019, 1, 27, 13, 11, 11, 249943, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='create_event',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2019, 1, 27, 13, 11, 11, 249943, tzinfo=utc)),
        ),
    ]
