# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-28 00:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('create_event', '0012_auto_20190128_0611'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Get_Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('Email', models.EmailField(max_length=150, unique=True)),
                ('Gender', models.CharField(choices=[('male', 'male'), ('Female', 'Female')], default='Male', max_length=150)),
                ('Age', models.IntegerField(default=0)),
                ('Cell_Phone', models.IntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create_event.Create_Event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
